### ISSUE TITLE
Some issues found

### ISSUE THREAD

**Issue by J0N-C** [Thraxs/NotD-Aftermath#1]
Chain explosive cases are spawning with only 2 charges
NPC nades still crashing the game
End game loss message just gives link to notd-aftermath.com, should be replaced with discord
Need to confirm if delta is able to use grenade? In a game, Thompson was dead, and when lyg walked over delta chains, the npc said "Fire in the hole!" but nothing happened.

**Comment by Thraxs** [comment]
Fixed for 1.0.2:
- Number of charges in chain explosive cases 
- NPC nades (disabled again like in 1.6a h1). Might come back in the future if I find a way to stop the crashes.
- Regarding the end game messages, I think I've replaced them all with the new link, www.notd.am, which is a new domain that redirects to discord. Let me know if you see any link to the old website again.
- Delta nades will be disabled too to avoid the crashes.

**Comment by Thraxs** [comment]
Version 1.0.2 released with fixes for these issues.
